version: '3.4'

services:
    SqlServerDb:
         container_name: SqlServerContainer
         image: mcr.microsoft.com/mssql/server:2017-latest
         ports:
             - 8000:1433
         environment:
             - ACCEPT_EULA=Y
             - MSSQL_SA_PASSWORD=myStong_Password123# 

    fiap.tech.ui:
        container_name: FiapUIContainer
        image: ${DOCKER_REGISTRY-}fiaptechui
        ports:
            - 8001:8081 
        build:
          context: .
          dockerfile: FIAP.TECH.UI/Dockerfile

    fiap.tech.api:
        container_name: FiapAPIContainer
        image: ${DOCKER_REGISTRY-}fiaptechapi
        ports:
            - 8002:8081 
        build:
            context: .
            dockerfile: FIAP.TECH.API/Dockerfile
        depends_on:
            - SqlServerDb

    fiap.tech.auth:
        container_name: FiapAUTHContainer
        image: ${DOCKER_REGISTRY-}fiaptechauth
        ports:
            - 8003:8081 
        build:
          context: .
          dockerfile: FIAP.TECH.AUTH/Dockerfile   
        depends_on:
            - SqlServerDb
